Parte acabada Practica 1 Oscar
Missionpage/sw-practices pull request #8
Opened 2022-02-23 23:51 UTC by otero00

Los enlaces a diferentes páginas están sin enlazar totalmente por la falta de vuestras respectivas partes. Si algo no funciona avisadme. Un saludo!!

2022-02-24 11:56 UTC, AlmuGSancha requested changes
En línea 19 poner:
<a href="detalles.html" >Detalles</a>

2022-02-24 11:56 UTC, AlmuGSancha commented on doc/web/index.html
> +	<div id=" barra_navegacion">
Falta detalles.html en la navegación

2022-02-25 19:37 UTC, Missionpage commented
He encontrado bastantes errores, sólo pasando el W3 Validator. Dejando de lado la indentación del código, los errores que he obtenido han sido los siguientes: 

![707bb86ff7bfb4e20bd5af516e690bfa](https://user-images.githubusercontent.com/26282994/155783885-0fe06f2b-aab5-4ed8-b165-5f3501205506.png)

![7e4c0e942301357c2e2fd1bbaee5f0b3](https://user-images.githubusercontent.com/26282994/155783808-7b2fd607-242f-49b8-989a-d61e8bee43be.png)

2022-02-25 20:02 UTC, Missionpage commented
Added "detalles.html" reference: https://github.com/Missionpage/sw-practices/pull/8#pullrequestreview-892339072

2022-02-25 20:03 UTC, merged